
# Docker

trigger:
  paths:
    include:
      - result/*

resources:
- repo: self

variables:

  dockerRegistryServiceConnection: '700d9717-406a-49b7-a070-35c833f14d2e'
  imageRepository: 'voteresultimage'
  containerRegistry: 'votingregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'azureagent'

stages:


- stage: Build
  displayName: Build

  jobs:

  - job: Buildforresult
    displayName: Buildforresult

    steps:

    - task: Docker@2
      displayName: Build the image for result microservice

      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'result/Dockerfile'
        tags: '$(tag)'




- stage: PushtoContainerRegistryforresult
  displayName: PushtoContainerRegistryforresult

  jobs:

  - job: PushtoContainerRegistryforresult
    displayName: PushtoContainerRegistryforresult

    steps:

    - task: Docker@2
      displayName: Push the image for result microservice

      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'



- stage: UpdateManifestsforresult
  displayName: UpdateManifestsforresult

  jobs:

  - job: UpdateManifestsforresult
    displayName: UpdateManifestsforresult

    steps:

    # Checkout repository
    - checkout: self
      persistCredentials: true

    # Run shell script
    - task: ShellScript@2
      displayName: Update Voting Kubernetes Manifest

      inputs:
        scriptPath: 'scripts/mainupdatemanifestscript.sh'
        args: 'vote $(imageRepository) $(tag)'

      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)


