# Docker

trigger:
  paths:
    include:
      - result/*

resources:
- repo: self

variables:
 
  dockerRegistryServiceConnection: '700d9717-406a-49b7-a070-35c833f14d2e'
  imageRepository: 'votingresultimage'
  containerRegistry: 'votingregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'azureagent'

stages:

- stage: Build
  displayName: Build 

  jobs:

  - job: Buildforresult
    displayName: Buildforresult


    steps:
    - task: Docker@2

      displayName: Build the image for result microservice
     
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'result/Dockerfile'
        tags: '$(tag)'

# ---X-----X

- stage: PushtoContainerRegistryforResult
  displayName: PushtoContainerRegistryforResult

  jobs:

  - job: PushtoContainerRegistryforresult
    displayName: PushtoContainerRegistryforresult


    steps:
    - task: Docker@2

      displayName: Build the image for result microservice
     
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'


