
# Docker

trigger:
  paths:
    include:
      - worker/*

resources:
- repo: self

variables:

  dockerRegistryServiceConnection: '700d9717-406a-49b7-a070-35c833f14d2e'
  imageRepository: 'worker'
  containerRegistry: 'votingregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/worker/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'azureagent'

stages:


- stage: Build
  displayName: Build

  jobs:

  - job: Buildforworker
    displayName: Buildforworker

    steps:

    - task: Docker@2
      displayName: Build the image for worker microservice

      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'worker/Dockerfile'
        tags: '$(tag)'




- stage: PushtoContainerRegistryforworker
  displayName: PushtoContainerRegistryforworker

  jobs:

  - job: PushtoContainerRegistryforworker
    displayName: PushtoContainerRegistryforworker

    steps:

    - task: Docker@2
      displayName: Push the image for worker microservice

      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'



- stage: UpdateManifestsforworker
  displayName: UpdateManifestsforworker

  jobs:

  - job: UpdateManifestsforworker
    displayName: UpdateManifestsforworker

    steps:

    # Checkout repository
    - checkout: self
      persistCredentials: true

    # Run shell script
    - task: ShellScript@2
      displayName: Update Voting Kubernetes Manifest

      inputs:
        scriptPath: 'scripts/mainupdatemanifestscript.sh'
        args: 'vote $(imageRepository) $(tag)'

      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)


